### ISSUE TITLE
Determining Youtube Endpoints

### ISSUE THREAD

**Issue by venegu** [Soother/Soothe#10]
You will need to figure out what endpoints and what data we will need fetch. Please post this information here. 

Additionally, create a mini example with a table view that displays a video of some sort using (no auto layout necessary) to a repo of your own. The reason being is that sometimes it's easier to implement complex things in a clean project then move it into a more complex project.

**Comment by Donateaz** [comment]
Links:
-https://github.com/OAuthSwift/OAuthSwift
-http://www.appcoda.com/youtube-api-ios-tutorial/
-https://stackoverflow.com/questions/36057734/youtube-api-beginner-searching-for-a-list-of-different-terms-automatically
-https://developers.google.com/youtube/v3/guides/ios_youtube_helper#installation
-https://developers.google.com/youtube/v3/docs/videos#properties
-(errors) https://developers.google.com/youtube/v3/docs/errors#activities_youtube.activities.list
